# Generated by Django 5.0.6 on 2024-07-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Txns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=66)),
                ('nonce', models.IntegerField()),
                ('block_hash', models.CharField(max_length=66)),
                ('transaction_index', models.IntegerField()),
                ('from_address', models.CharField(max_length=42)),
                ('to_address', models.CharField(max_length=42)),
                ('value', models.CharField(max_length=255)),
                ('gas', models.CharField(max_length=255)),
                ('gas_price', models.CharField(max_length=255)),
                ('is_error', models.BooleanField(max_length=255)),
                ('txreceipt_status', models.BooleanField()),
                ('input', models.CharField(max_length=255)),
                ('contract_address', models.CharField(max_length=255)),
                ('cumulative_gas_used', models.CharField(max_length=255)),
                ('gas_used', models.CharField(max_length=255)),
                ('confirmations', models.CharField(max_length=255)),
                ('method_id', models.CharField(max_length=255)),
                ('function_name', models.CharField(max_length=255)),
            ],
        ),
    ]
