# Generated by Django 5.0.6 on 2024-07-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_txns_txn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='txn',
            options={'ordering': ['timestamp']},
        ),
    ]
