# Generated by Django 5.0.6 on 2024-07-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_txn_is_error_alter_txn_txreceipt_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='txn',
            options={'ordering': ['-timestamp']},
        ),
    ]
